"""Report writers: self-contained HTML, JSON and Markdown."""

from __future__ import annotations

import json
import os
import time
from typing import Optional

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")


def _load_template(name: str = "report.html") -> str:
    with open(os.path.join(TEMPLATE_DIR, name), "r", encoding="utf-8") as fh:
        return fh.read()


def _slim(result: dict, max_files: int = 1500) -> dict:
    """Trim payload so the HTML stays small on huge repositories."""
    slim = dict(result)
    files = result.get("files", [])
    if len(files) > max_files:
        slim["files"] = files[:max_files]
    return slim


def render_html(result: dict) -> str:
    payload = json.dumps(_slim(result), ensure_ascii=False, separators=(",", ":"))
    # Keep the JSON safe inside a <script> block.
    payload = payload.replace("</", "<\\/")
    html = _load_template()
    html = html.replace("__REPO_NAME__", result["summary"]["repository"])
    html = html.replace("__REPOLENS_DATA__", payload)
    return html


def write_html(result: dict, path: str) -> str:
    html = render_html(result)
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)
    return path


def write_json(result: dict, path: str, indent: int = 2) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(result, fh, ensure_ascii=False, indent=indent)
    return path


def render_markdown(result: dict, top: int = 10) -> str:
    """Markdown summary — designed to be pasted into a PR comment."""
    s = result["summary"]
    lines = []
    lines.append(f"## RepoLens report · `{s['repository']}` ({s['branch']})")
    lines.append("")
    lines.append(f"**Health score: {s['health_score']}/100**")
    lines.append("")
    lines.append("| Dimension | Score | Detail |")
    lines.append("| --- | ---: | --- |")
    for dim in s["health_dimensions"]:
        lines.append(f"| {dim['name']} | {dim['score']} | {dim['detail']} |")
    lines.append("")
    bf = s["bus_factor"]
    lines.append(
        f"{s['commits']} commits · {s['authors']} authors · {s['analysed_files']} files · "
        f"{s['loc']:,} LOC · bus factor {bf['bus_factor']}"
    )
    lines.append("")
    lines.append(f"### Top {top} hotspots")
    lines.append("")
    lines.append("| File | Risk | LOC | Commits | Authors | Why |")
    lines.append("| --- | ---: | ---: | ---: | ---: | --- |")
    for rep in result["hotspots"][:top]:
        why = "; ".join(rep["reasons"]) or "-"
        lines.append(
            f"| `{rep['path']}` | {rep['risk']:.0f} | {rep['loc']} | {rep['commits']} | "
            f"{rep['authors']} | {why} |"
        )
    if result["quick_wins"]:
        lines.append("")
        lines.append("### Quick wins")
        lines.append("")
        for q in result["quick_wins"]:
            lines.append(f"- `{q['path']}` — risk {q['risk']:.0f}, {q['loc']} LOC ({'; '.join(q['reasons']) or 'sizeable and churny'})")
    if result["knowledge_risk"]:
        lines.append("")
        lines.append("### Knowledge risk")
        lines.append("")
        for k in result["knowledge_risk"][:5]:
            lines.append(f"- `{k['path']}` — {k['author']} owns {k['ownership'] * 100:.0f}% of {k['commits']} commits")
    if result["coupling"]:
        lines.append("")
        lines.append("### Temporal coupling")
        lines.append("")
        for c in result["coupling"][:5]:
            lines.append(f"- `{c['a']}` ↔ `{c['b']}` — together in {c['shared']} commits ({c['ratio'] * 100:.0f}%)")
    lines.append("")
    lines.append(f"<sub>Generated by RepoLens at {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime(s['generated_at']))}</sub>")
    lines.append("")
    return "\n".join(lines)


def write_markdown(result: dict, path: str, top: int = 10) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render_markdown(result, top=top))
    return path
