#!/usr/bin/env python3
"""第 10 课：生成与 simple_world.sdf 完全一致的导航地图。

地图 = learn_map.pgm（灰度图）+ learn_map.yaml（元数据）。
栅格语义（map_server 三值模式）:
    白(254) = 空闲   黑(0) = 障碍   灰(128) = 未知
    occupancy = (255 - pixel) / 255
    occ > occupied_thresh(0.65) -> 障碍; occ < free_thresh(0.25) -> 空闲; 其它 -> 未知

世界内容（必须与 07 课 simple_world.sdf 保持一致）:
    - 四面墙: 中心 ±5.0，厚 0.2（占据 [4.9, 5.1]）
    - box1:     中心 (2.0, 1.0), 边长 0.6, 旋转 0.4 rad
    - box2:     中心 (-2.0, -1.5), 边长 0.8, 旋转 -0.3 rad
    - cylinder: 中心 (0.0, 2.5), 半径 0.4
    - 机器人出生点 (-2.0, 0.0) 必须保持空闲

运行:
    python3 scripts/gen_map.py   （在 10-nav2-navigation 目录下）
"""

import math
import os

RES = 0.05          # 米/栅格
EXTENT = 10.4       # 覆盖到墙外侧
SIZE = int(round(EXTENT / RES))   # 208 x 208
ORIGIN = -EXTENT / 2.0

FREE, OCCUPIED, UNKNOWN = 254, 0, 128

# 障碍物定义（与 SDF 对应，略微膨胀 1~2cm 更安全）
BOX1 = dict(cx=2.0, cy=1.0, half=0.31, yaw=0.4)
BOX2 = dict(cx=-2.0, cy=-1.5, half=0.41, yaw=-0.3)
CYL = dict(cx=0.0, cy=2.5, r=0.41)


def in_rotated_box(x, y, box):
    """点是否在以 (cx, cy) 为中心、旋转 yaw 的正方形内。"""
    dx, dy = x - box['cx'], y - box['cy']
    c, s = math.cos(-box['yaw']), math.sin(-box['yaw'])
    rx = dx * c - dy * s
    ry = dx * s + dy * c
    return abs(rx) <= box['half'] and abs(ry) <= box['half']


def cell_value(x, y):
    # 四面墙（占据 |x| 或 |y| 在 [4.9, 5.1] 内的区域）
    if abs(x) >= 4.89 or abs(y) >= 4.89:
        return OCCUPIED
    if in_rotated_box(x, y, BOX1):
        return OCCUPIED
    if in_rotated_box(x, y, BOX2):
        return OCCUPIED
    if (x - CYL['cx']) ** 2 + (y - CYL['cy']) ** 2 <= CYL['r'] ** 2:
        return OCCUPIED
    return FREE


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(here, '..', 'src', 'nav2_demo', 'maps')
    os.makedirs(out_dir, exist_ok=True)

    # PGM: 行 0 = 图像顶部 = 最大 y
    rows = []
    for r in range(SIZE):
        y = ORIGIN + (SIZE - 1 - r + 0.5) * RES
        row = bytearray()
        for c in range(SIZE):
            x = ORIGIN + (c + 0.5) * RES
            row.append(cell_value(x, y))
        rows.append(bytes(row))

    pgm_path = os.path.join(out_dir, 'learn_map.pgm')
    with open(pgm_path, 'wb') as f:
        f.write(f'P5\n# generated by gen_map.py\n{SIZE} {SIZE}\n255\n'.encode())
        for row in rows:
            f.write(row)

    yaml_path = os.path.join(out_dir, 'learn_map.yaml')
    with open(yaml_path, 'w') as f:
        f.write(
            'image: learn_map.pgm\n'
            'mode: trinary\n'
            f'resolution: {RES}\n'
            f'origin: [{ORIGIN}, {ORIGIN}, 0]\n'
            'negate: 0\n'
            'occupied_thresh: 0.65\n'
            'free_thresh: 0.25\n'
        )

    print(f'已生成: {pgm_path}')
    print(f'已生成: {yaml_path}')


if __name__ == '__main__':
    main()
